name: Default workflow

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5

  release-please:
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.AUTERION_CI_ACCESS_TOKEN }}
          release-type: simple
          package-name: auterion-pre-commit-hooks
